apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: scheduling.kube-valet.io
webhooks:
- name: scheduling.kube-valet.io
  failurePolicy: Fail
  clientConfig:
    url: "https://192.168.1.6:9443/mutate"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI4RENDQVpXZ0F3SUJBZ0lVQ0RwTVNENkFnS2Z5d3Y5ci9JMkpBTFdUR2FNd0NnWUlLb1pJemowRUF3SXcKVFRFTE1Ba0dBMVVFQmhNQ1ZWTXhDekFKQmdOVkJBZ1RBbFZVTVE0d0RBWURWUVFIRXdWUWNtOTJiekVoTUI4RwpBMVVFQXhNWWMyTm9aV1IxYkdsdVp5NXJkV0psTFhaaGJHVjBMbWx2TUI0WERURTVNRGN5TWpFNE1qTXdNRm9YCkRUSTBNRGN5TURFNE1qTXdNRm93VFRFTE1Ba0dBMVVFQmhNQ1ZWTXhDekFKQmdOVkJBZ1RBbFZVTVE0d0RBWUQKVlFRSEV3VlFjbTkyYnpFaE1COEdBMVVFQXhNWWMyTm9aV1IxYkdsdVp5NXJkV0psTFhaaGJHVjBMbWx2TUZrdwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWRTVUVhc3BhU0NoSzlKdVp1dUxBd1FFNzczdXZzVzlWCkJweGY3OXdudGZLSndpT0JjaVNuNUZRR1VUNDNxNm5Ga3dWRmgzbUIrcnJraXlKZkFFNXNjcU5UTUZFd0RnWUQKVlIwUEFRSC9CQVFEQWdFR01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDb3NJRHlOaVZ5NQpoZGJiUDUya3lnLzhRYU5WTUE4R0ExVWRFUVFJTUFhSEJNQ29BUVl3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loCkFPVkdNYkdUWGhmNzZXZ2FKQlN5RmVrN2xsRmtmc1Fpdm9aM3FGMjV6ekxPQWlFQXlrUTZaRVJYakR2NVVDL3kKSERSL01ac2ltd2NoRWJqWmlQcmk0cFJjSC9nPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["*"]
    resources: ["pods"]
    scope: "*"
